#!/bin/bash

# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache 2.0 License.

# This product includes software developed at
# Datadog (https://www.datadoghq.com/)
# Copyright 2025-present Datadog, Inc.

# This script combines all open Dependabot PRs into a single PR by cherry-picking their commits.

set -e

# Color codes
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
RED="\033[0;31m"
BLUE="\033[0;34m"
RESET="\033[0m"

echo -e "${BLUE}🔍 Combine Dependabot PRs Script${RESET}"
echo ""

# Store original HEAD for safety
ORIGINAL_HEAD=$(git rev-parse HEAD)

# Prerequisites check
echo -e "${YELLOW}Checking prerequisites...${RESET}"

if ! command -v gh &> /dev/null; then
    echo -e "${RED}❌ Error: gh CLI is not installed${RESET}"
    echo "Install from: https://cli.github.com/"
    exit 1
fi

if ! command -v git &> /dev/null; then
    echo -e "${RED}❌ Error: git is not installed${RESET}"
    exit 1
fi

# Check gh authentication
if ! gh auth status &> /dev/null; then
    echo -e "${RED}❌ Error: gh CLI is not authenticated${RESET}"
    echo "Run: gh auth login"
    exit 1
fi

# Check working tree is clean
if [[ -n $(git status --porcelain) ]]; then
    echo -e "${RED}❌ Error: Working tree is not clean${RESET}"
    echo "Please commit or stash your changes first"
    git status --short
    exit 1
fi

echo -e "${GREEN}✅ Prerequisites OK${RESET}"
echo ""

# Fetch all open Dependabot PRs
echo -e "${YELLOW}Fetching open Dependabot PRs...${RESET}"

PR_DATA=$(gh pr list \
  --state open \
  --author "app/dependabot" \
  --json number,title,headRefName,url,mergeable \
  --limit 100)

if [[ -z "$PR_DATA" ]] || [[ "$PR_DATA" == "[]" ]]; then
    echo -e "${YELLOW}⚠️  No open Dependabot PRs found${RESET}"
    exit 0
fi

# Parse and sort PRs by number (bash 3.2 compatible)
declare -a PR_LINES
while IFS= read -r line; do
    PR_LINES+=("$line")
done < <(echo "$PR_DATA" | jq -r 'sort_by(.number) | .[] | select(.mergeable == "MERGEABLE") | "\(.number)|\(.title)|\(.headRefName)|\(.url)"')

if [[ ${#PR_LINES[@]} -eq 0 ]]; then
    echo -e "${YELLOW}⚠️  No mergeable Dependabot PRs found${RESET}"
    exit 0
fi

echo -e "${GREEN}✅ Found ${#PR_LINES[@]} mergeable Dependabot PR(s)${RESET}"
echo ""

# Arrays to track results
declare -a SUCCESSFUL_PRS
declare -a FAILED_PRS

# Cherry-pick loop
for pr_line in "${PR_LINES[@]}"; do
    IFS='|' read -r PR_NUM PR_TITLE HEAD_REF PR_URL <<< "$pr_line"

    echo -e "${BLUE}Processing PR #${PR_NUM}: ${PR_TITLE}${RESET}"

    # Get commit SHA
    COMMIT_SHA=$(git rev-parse "origin/${HEAD_REF}" 2>/dev/null || echo "")

    if [[ -z "$COMMIT_SHA" ]]; then
        echo -e "${RED}  ❌ Failed to get commit SHA for ${HEAD_REF}${RESET}"
        FAILED_PRS+=("${PR_NUM}|${PR_TITLE}|${PR_URL}|Failed to fetch commit")
        continue
    fi

    # Check if already applied
    if git merge-base --is-ancestor "${COMMIT_SHA}" HEAD 2>/dev/null; then
        echo -e "${YELLOW}  ⏭️  Already applied, skipping${RESET}"
        SUCCESSFUL_PRS+=("${PR_NUM}|${PR_TITLE}|${PR_URL}")
        continue
    fi

    # Attempt cherry-pick (disable set -e temporarily)
    set +e
    CHERRY_PICK_OUTPUT=$(git cherry-pick "${COMMIT_SHA}" 2>&1)
    CHERRY_PICK_EXIT=$?
    set -e

    if [[ $CHERRY_PICK_EXIT -eq 0 ]]; then
        echo -e "${GREEN}  ✅ Successfully cherry-picked${RESET}"
        SUCCESSFUL_PRS+=("${PR_NUM}|${PR_TITLE}|${PR_URL}")
    else
        echo -e "${RED}  ❌ Cherry-pick failed (conflict)${RESET}"
        git cherry-pick --abort 2>/dev/null || true
        FAILED_PRS+=("${PR_NUM}|${PR_TITLE}|${PR_URL}|Cherry-pick conflict")
    fi
    echo ""
done

# Generate PR description
echo -e "${YELLOW}Generating PR description...${RESET}"

PR_DESCRIPTION="## Combined Dependabot Updates

This PR combines ${#SUCCESSFUL_PRS[@]} Dependabot PR(s) into a single update.

### Included PRs
"

for pr_data in "${SUCCESSFUL_PRS[@]}"; do
    IFS='|' read -r PR_NUM PR_TITLE PR_URL <<< "$pr_data"
    PR_DESCRIPTION+="- #${PR_NUM} - ${PR_TITLE}
"
done

PR_DESCRIPTION+="
### Summary
- ✅ Successfully combined: ${#SUCCESSFUL_PRS[@]} PR(s)
"

if [[ ${#FAILED_PRS[@]} -gt 0 ]]; then
    PR_DESCRIPTION+="- ❌ Skipped (conflicts): ${#FAILED_PRS[@]} PR(s)

### Skipped PRs (manual merge required)
"
    for pr_data in "${FAILED_PRS[@]}"; do
        IFS='|' read -r PR_NUM PR_TITLE PR_URL REASON <<< "$pr_data"
        PR_DESCRIPTION+="- #${PR_NUM} - ${PR_TITLE} - ${PR_URL} (${REASON})
"
    done
fi

PR_DESCRIPTION+="
---
🤖 Generated by combine-dependabot-prs.sh"

# Check if there were any successful cherry-picks
if [[ ${#SUCCESSFUL_PRS[@]} -eq 0 ]]; then
    echo -e "${RED}❌ No PRs were successfully combined${RESET}"
    echo "All PRs had conflicts. Manual intervention required."
    exit 1
fi

# Push branch
echo -e "${YELLOW}Pushing branch to origin...${RESET}"
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

if git push -u origin "${CURRENT_BRANCH}" 2>&1; then
    echo -e "${GREEN}✅ Branch pushed${RESET}"
else
    echo -e "${RED}❌ Failed to push branch${RESET}"
    exit 1
fi
echo ""

# Create PR
echo -e "${YELLOW}Creating pull request...${RESET}"

PR_TITLE="chore(deps): combine Dependabot updates"

if PR_OUTPUT=$(gh pr create \
    --base main \
    --title "${PR_TITLE}" \
    --body "${PR_DESCRIPTION}" \
    --no-maintainer-edit 2>&1); then
    echo -e "${GREEN}✅ Pull request created${RESET}"
    echo ""
    echo -e "${GREEN}${PR_OUTPUT}${RESET}"
    COMBINED_PR_URL="$PR_OUTPUT"
else
    echo -e "${RED}❌ Failed to create PR${RESET}"
    echo "$PR_OUTPUT"
    exit 1
fi
echo ""

# Close original Dependabot PRs
echo -e "${YELLOW}Closing original Dependabot PRs...${RESET}"
CLOSE_COMMENT="This PR has been combined into ${COMBINED_PR_URL} and will be merged there.

🤖 Automatically closed by combine-dependabot-prs.sh"

for pr_data in "${SUCCESSFUL_PRS[@]}"; do
    IFS='|' read -r PR_NUM PR_TITLE PR_URL <<< "$pr_data"

    echo -e "${BLUE}  Closing PR #${PR_NUM}...${RESET}"

    if gh pr close "${PR_NUM}" --comment "${CLOSE_COMMENT}" 2>&1; then
        echo -e "${GREEN}    ✅ Closed${RESET}"
    else
        echo -e "${YELLOW}    ⚠️  Failed to close (may require manual intervention)${RESET}"
    fi
done
echo -e "${GREEN}✅ Original PRs closed${RESET}"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${GREEN}🎉 Success!${RESET}"
echo ""
echo -e "${GREEN}✅ Successfully combined: ${#SUCCESSFUL_PRS[@]} PR(s)${RESET}"

if [[ ${#FAILED_PRS[@]} -gt 0 ]]; then
    echo -e "${RED}❌ Skipped: ${#FAILED_PRS[@]} PR(s)${RESET}"
    echo ""
    echo "Skipped PRs:"
    for pr_data in "${FAILED_PRS[@]}"; do
        IFS='|' read -r PR_NUM PR_TITLE PR_URL REASON <<< "$pr_data"
        echo -e "  - ${RED}#${PR_NUM}${RESET} - ${PR_TITLE}"
    done
    echo ""
    echo "These PRs will need to be merged manually."
fi

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
