apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  labels:
    cloud.googleapis.com/location: <LOCATION>
    service: <SERVICE_NAME>
  name: <APP_NAME>
  namespace: <PROJECT_NUMBER>
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '2'
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/container-dependencies: '{"":["datadog-sidecar"]}'
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/sessionAffinity: 'false'
      labels:
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: DD_LOG_LEVEL
          value: debug
        - name: DD_TRACE_DEBUG
          value: 'true'
        - name: DD_SERVERLESS_LOG_PATH
          value: /shared-logs/logs/*.log
        - name: DD_SERVICE
          value: <SERVICE_NAME>
        image: <DOCKER_IMAGE>
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
        volumeMounts:
        - mountPath: /shared-logs
          name: shared-logs
      - env:
        - name: DD_ENV
          value: dev
        - name: DD_SITE
          value: datadoghq.com
        - name: DD_LOG_LEVEL
          value: debug
        - name: DD_API_KEY
          value: <DD_API_KEY>
        - name: DD_HEALTH_PORT
          value: '9999'
        - name: DD_TAGS
          value: deployed-with:yaml
        - name: DD_SERVERLESS_LOG_PATH
          value: /shared-logs/logs/*.log
        - name: DD_SERVICE
          value: <SERVICE_NAME>
        - name: DD_VERSION
          value: '1'
        image: gcr.io/datadoghq/serverless-init:latest
        name: datadog-sidecar
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          tcpSocket:
            port: 9999
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /shared-logs
          name: shared-logs
      serviceAccountName: <SERVICE_ACCOUNT_EMAIL>
      timeoutSeconds: 5
      volumes:
      - emptyDir:
          medium: Memory
        name: shared-logs
  traffic:
  - latestRevision: true
    percent: 100
